### ISSUE TITLE
Request duration calculation unclear

### ISSUE THREAD

**Issue by Licenser** [wayfair-incubator/minigun#12]
## Description

In the upper summary the field `Request duration` seems to be calculated by including concurrency into the calculations. That is problematic when looking at durations/latencies.

Unlike throughput ( `requests / s` the field about) where a higher concurrency is directly related to the result for latency, this can't be calculated this way - latency remains largely unaffected by concurrency. Or in other words (ignoring server limits) doubling the concurrency doubles the throughput but the latency remains the same.

This is in so far problematic that it gives the misleading impression that higher concurrency results in lower latencies, if these numbers are used to measure SLA's / SLO's they won't reflect the latency/duration of requests in a realistic way.

## Expected Behaviour

The `Request duraction` to be calculated based on the latency of the requests not as `total time / (requests/s)`. Reflecting the numbers in the detailed stats below.

## Actual Behaviour

The `Request duraction` is calculated with the assumption that concurrency linearly impacts latency.

## Affected Version

latest

## Steps to Reproduce

1. run a test w/ concurrency = 1
2. run a test w/ concurrency = 2
3. compare `Request duration` it will have approximately halved while in reality, the duration of a request has not changed significantly

## Checklist

- [X] I have read the [contributing guidelines](https://github.com/wayfair-incubator/minigun/blob/main/CONTRIBUTING.md)
- [x] I have verified this does not duplicate an existing issue

**Comment by adidenko** [comment]
This is not a bug, this is by design. Some other well-known benchmarks use the same approach, so we have it in Minigun for compatibility with those benchmarks. Here's an example from Apache Benchmark:

```
Concurrency Level:      5
Time taken for tests:   6.348 seconds
Complete requests:      100
Requests per second:    15.75 [#/sec] (mean)
Time per request:       317.408 [ms] (mean)
Time per request:       63.482 [ms] (mean, across all concurrent requests)
```

```
Concurrency Level:      10
Time taken for tests:   3.410 seconds
Complete requests:      100
Requests per second:    29.32 [#/sec] (mean)
Time per request:       341.044 [ms] (mean)
Time per request:       34.104 [ms] (mean, across all concurrent requests)
```

This is also explained in https://github.com/wayfair-incubator/minigun/blob/main/docs/report-help.md

If you want to measure your service's response time for SLI/SLO, then it's better to use `Full request duration` (in JSON `.FullRequestDurationSecondsMean` or even better `.FullRequestDurationSecondsQuantiles`).

I think we can remove that `Request duration` from the report to avoid confusion.
